# Generated by Django 2.2.5 on 2020-05-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.IntegerField()),
            ],
            options={
                'db_table': 'student_teacher_follow',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=128)),
                ('signature', models.TextField(max_length=128, null=True)),
                ('photo_url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=128)),
                ('signature', models.TextField(max_length=128, null=True)),
                ('photo_url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacherKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserModel.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='studentKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserModel.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(through='UserModel.follow', to='UserModel.Teacher'),
        ),
        migrations.AddField(
            model_name='follow',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserModel.Student'),
        ),
        migrations.AddField(
            model_name='follow',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserModel.Teacher'),
        ),
    ]
