# Generated by Django 2.2.5 on 2020-06-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='teacher',
            name='major',
            field=models.CharField(default='', max_length=256),
        ),
    ]
