# Generated by Django 2.2.5 on 2020-06-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0002_auto_20200618_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentkeyword',
            old_name='student',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='teacherkeyword',
            old_name='teacher',
            new_name='Teacher',
        ),
    ]
