# Generated by Django 2.2.5 on 2020-06-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0003_auto_20200618_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='old',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='old',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
