# Generated by Django 2.2.5 on 2020-06-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0004_auto_20200619_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
    ]
