# Generated by Django 2.2.5 on 2020-06-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0006_auto_20200620_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=256)),
                ('send_user', models.CharField(default='', max_length=128)),
                ('recive_user', models.CharField(default='', max_length=128)),
                ('data_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
