# Generated by Django 2.2.5 on 2020-06-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0007_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='signature',
        ),
        migrations.AddField(
            model_name='student',
            name='skill',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='skill',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo_url',
            field=models.TextField(default=''),
        ),
    ]
